### ISSUE TITLE
Does not work with the latest Rust nightlies

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/afl.rs#101]
Stopped working after https://github.com/rust-lang/rust/commit/3fd5fdd8d3e64e957a7eafe3d6d0b10ef4170d59

Output I get when I try to compile a Rust version after the change above: https://gist.githubusercontent.com/frewsxcv/ca3ef34cab9fd96edd44fc5de585044d/raw/837b8b6ccbfa682a34977233f535c186e4375c93/gistfile1.txt

A lot of errors like:

```
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-0.4.2/src/par_iter/weight.rs:48: undefined reference to `__afl_prev_loc'
```

**Comment by frewsxcv** [comment]
For the record, one can reproduce this issue by building this crate: https://github.com/frewsxcv/rust-belt-rust-fuzzing-workshop/tree/master/exercise2/jpeg-decoder

**Comment by frewsxcv** [comment]
Added a branch with minimal changes to reproduce this issue. Just run `./reproduce-issue.sh`

**Comment by frewsxcv** [comment]
First nightly it fails on: `2016-09-15`. Last nightly it works on: `2016-09-13`.

**Comment by frewsxcv** [comment]
Might be related to https://github.com/rust-lang/rust/issues/39782

Might be worth trying to use rustc's LLVM it builds instead of relying on the system one

**Comment by frewsxcv** [comment]
should be resolved with the new version https://users.rust-lang.org/t/announcing-afl-rs-0-2-bindings-for-american-fuzzy-lop/13981
